# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.hostname = "lx-gitlab-01"

  config.vm.network "forwarded_port",id: "http", guest: 80, host: 8081, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port",id: "https/ssl", guest: 443, host: 8443, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port",id: "ssh", guest: 22, host: 2202, host_ip: "127.0.0.1", auto_correct: false

  # Disable updating guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "GitLab Node"
  end

end
